import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from '@/shared/contexts/auth-context';
import { ReactQueryProvider } from '@/shared/lib/react-query/provider';
import { MaterialUIProvider } from '@/shared/providers/material-ui-provider';
import { NotificationContainer } from '@/shared/components/notification/notification-container';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <MaterialUIProvider>
          <ReactQueryProvider>
            <AuthProvider>
              {children}
              <NotificationContainer />
            </AuthProvider>
          </ReactQueryProvider>
        </MaterialUIProvider>
      </body>
    </html>
  );
}
